yolo:
  # Use your custom detector; if weights_url is set and file missing/LFS, it will be downloaded
  weights_path: weights/yolo.pt
  weights_url: "https://huggingface.co/Krizz9/yolo/resolve/main/yolo.pt?download=true"
  conf_threshold: 0.25
  iou_threshold: 0.45
  target_class_name: id  # change to your YOLO class name for ID documents

classification:
  efficientnet:
    model_name: efficientnet_b0
    weights_path: weights/efficientnet.keras
    weights_url: "https://huggingface.co/Krizz9/efficient/resolve/main/efficientnet.keras?download=true"
    num_classes: 3
    class_names: [ktp, passport, sim]
  mobilenet:
    model_name: mobilenet_v2
    weights_path: weights/mobilenet.keras
    weights_url: "https://huggingface.co/Krizz9/mobile/resolve/main/mobilenet.keras?download=true"
    num_classes: 3
    class_names: [ktp, passport, sim]
  topk: 3